int BRICK_WIDTH = 30;
int BRICK_HEIGHT = 12;
int BRICK_COUNT = 20;
int CANVAS_HEIGHT = 500;
int CANVAS_WIDTH = 1000;
int STARTING_X = CANVAS_WIDTH / 2 - ((BRICKS_IN_BASE / 2) * BRICK_WIDTH);
int STARTING_Y = CANVAS_HEIGHT - BRICK_HEIGHT;
int INCREASE;

void setup(){
  size(1000, 500);
}
void draw(){
  for(INCREASE = 0; INCREASE<BRICK_COUNT; INCREASE++){
  for(int i = 0; i<BRICK_COUNT-INCREASE; i++){
  rect(STARTING_X+((BRICK_WIDTH/2)*INCREASE)+(i*BRICK_WIDTH), STARTING_Y-((BRICK_HEIGHT)*INCREASE), BRICK_WIDTH, BRICK_HEIGHT);
  }
  }
} 